Config = Config or {}
Config.BillingCommissions = { -- This is a percentage (0.10) == 10%
    mechanic = 0.10
}
Config.Linux = false      -- True if linux
Config.TweetDuration = 12 -- How many hours to load tweets (12 will load the past 12 hours of tweets)
Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 'M'

-- Set this to true if you wish to use Fivemerr (https://fivemerr.com/) for media uploads. 
-- Ensure to add your API key to server/main.lua 
Config.Fivemerr = false

Config.PhoneApplications = {
    ['phone'] = {
        app = 'phone',
        color = '#04b543',
        icon = 'fa fa-phone-alt',
        tooltipText = '电话',
        tooltipPos = 'top',
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ['whatsapp'] = {
        app = 'whatsapp',
        color = '#25d366',
        icon = 'fas fa-comment',
        tooltipText = '微信',
        tooltipPos = 'top',
        style = 'font-size: 2.8vh',
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ['settings'] = {
        app = 'settings',
        color = '#636e72',
        icon = 'fa fa-cogs',
        tooltipText = '设置',
        tooltipPos = 'top',
        style = 'padding-right: .08vh; font-size: 2.3vh',
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ['twitter'] = {
        app = 'twitter',
        color = '#1da1f2',
        icon = 'fab fa-twitter',
        tooltipText = '推特',
        tooltipPos = 'top',
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ['garage'] = {
        app = 'garage',
        color = '#575fcf',
        icon = 'fas fa-car',
        tooltipText = '载具',
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ['mail'] = {
        app = 'mail',
        color = '#ff002f',
        icon = 'fas fa-envelope-open-text',
        tooltipText = '邮件',
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ['advert'] = {
        app = 'advert',
        color = '#ff8f1a',
        icon = 'fas fa-bullhorn',
        tooltipText = '广告',
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ['bank'] = {
        app = 'bank',
        color = '#9c88ff',
        icon = 'fas fa-money-check-alt',
        tooltipText = '网上银行',
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    ['crypto'] = {
        app = 'crypto',
        color = '#004682',
        icon = 'fas fa-coins',
        tooltipText = '虚拟货币',
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ['racing'] = {
        app = 'racing',
        color = '#353b48',
        icon = 'fas fa-flag-checkered',
        tooltipText = '比赛',
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ['houses'] = {
        app = 'houses',
        color = '#27ae60',
        icon = 'fas fa-home',
        tooltipText = '房产',
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
    ['lawyers'] = {
        app = 'lawyers',
        color = '#26d4ce',
        icon = 'fas fa-briefcase',
        tooltipText = '服务',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ['gallery'] = {
        app = 'gallery',
        color = '#AC1D2C',
        icon = 'fas fa-images',
        tooltipText = '相册',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ['camera'] = {
        app = 'camera',
        color = '#AC1D2C',
        icon = 'fas fa-camera',
        tooltipText = '相机',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
    ['meos'] = {
        app = 'meos',
        color = '#004682',
        icon = 'fas fa-ad',
        tooltipText = '移动数据终端',
        job = 'police',
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
}
Config.MaxSlots = 20

Config.StoreApps = {
    ['territory'] = {
        app = 'territory',
        color = '#353b48',
        icon = 'fas fa-globe-europe',
        tooltipText = '领土',
        tooltipPos = 'right',
        style = '',
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
        password = true,
        creator = 'QBCore',
        title = 'Territory',
    },
}
