QBShared = QBShared or {}
QBShared.Items = {
    -- 武器
    -- 玩意儿
    weapon_unarmed               = { name = 'weapon_unarmed', label = '拳头', weight = 1000, type = 'weapon', ammotype = nil, image = 'placeholder.png', unique = true, useable = false, description = '拳击' },
    weapon_dagger                = { name = 'weapon_dagger', label = '匕首', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_dagger.png', unique = true, useable = false, description = '一种短刀，刀片尖锐且有刃，常用作武器' },
    weapon_bat                   = { name = 'weapon_bat', label = '棒球棍', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_bat.png', unique = true, useable = false, description = '用于击打球类的体育器械（或其他物品）' },
    weapon_bottle                = { name = 'weapon_bottle', label = '破瓶子', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_bottle.png', unique = true, useable = false, description = '一瓶破碎的瓶子' },
    weapon_crowbar               = { name = 'weapon_crowbar', label = '撬棍', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_crowbar.png', unique = true, useable = false, description = '一种铁棍，带有扁平的端，用作杠杆' },
    weapon_flashlight            = { name = 'weapon_flashlight', label = '手电筒', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_flashlight.png', unique = true, useable = false, description = '一种电池驱动的便携灯' },
    weapon_golfclub              = { name = 'weapon_golfclub', label = '高尔夫球杆', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_golfclub.png', unique = true, useable = false, description = '用于击打高尔夫球的球杆' },
    weapon_hammer                = { name = 'weapon_hammer', label = '锤子', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_hammer.png', unique = true, useable = false, description = '用于破坏物体（如腿）和钉入钉子的工具' },
    weapon_hatchet               = { name = 'weapon_hatchet', label = '小斧头', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_hatchet.png', unique = true, useable = false, description = '一种小型斧头，带有短柄，可单手使用' },
    weapon_knuckle               = { name = 'weapon_knuckle', label = '拳套', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_knuckle.png', unique = true, useable = false, description = '一种金属护具，戴在拳头上，用于增强打击力' },
    weapon_knife                 = { name = 'weapon_knife', label = '刀', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_knife.png', unique = true, useable = false, description = '一种由刀片和刀柄组成的工具，用于切割或作为武器' },
    weapon_machete               = { name = 'weapon_machete', label = '弯刀', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_machete.png', unique = true, useable = false, description = '一种宽大、沉重的刀，常用作武器' },
    weapon_switchblade           = { name = 'weapon_switchblade', label = '弹簧刀', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_switchblade.png', unique = true, useable = false, description = '一种刀，按下按钮后刀片从刀柄中弹出' },
    weapon_nightstick            = { name = 'weapon_nightstick', label = '警棍', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_nightstick.png', unique = true, useable = false, description = '警察使用的棍棒' },
    weapon_wrench                = { name = 'weapon_wrench', label = '扳手', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_wrench.png', unique = true, useable = false, description = '一种用来夹住和旋转螺母、螺栓、管道等的工具' },
    weapon_battleaxe             = { name = 'weapon_battleaxe', label = '战斧', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_battleaxe.png', unique = true, useable = false, description = '一种大型的宽刃斧，常用于古代战争' },
    weapon_poolcue               = { name = 'weapon_poolcue', label = '台球杆', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_poolcue.png', unique = true, useable = false, description = '用于击打台球的杆' },
    weapon_briefcase             = { name = 'weapon_briefcase', label = '公文包', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_briefcase.png', unique = true, useable = false, description = '用于存放重要文件的公文包' },
    weapon_briefcase_02          = { name = 'weapon_briefcase_02', label = '行李箱', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_briefcase2.png', unique = true, useable = false, description = '适合到自由城度假使用' },
    weapon_garbagebag            = { name = 'weapon_garbagebag', label = '垃圾袋', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_garbagebag.png', unique = true, useable = false, description = '一个垃圾袋' },
    weapon_handcuffs             = { name = 'weapon_handcuffs', label = '手铐', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_handcuffs.png', unique = true, useable = false, description = '一对用于固定囚犯手腕的锁扣' },
    weapon_bread                 = { name = 'weapon_bread', label = '法棍面包', weight = 1000, type = 'weapon', ammotype = nil, image = 'baquette.png', unique = true, useable = false, description = '面包...?' },
    weapon_stone_hatchet         = { name = 'weapon_stone_hatchet', label = '石斧', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_stone_hatchet.png', unique = true, useable = true, description = '石斧' },
    weapon_candycane             = { name = 'weapon_candycane', label = '糖果拐杖', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_candycane', unique = true, useable = true, description = '糖果拐杖' },

    -- 手枪
    weapon_pistol                = { name = 'weapon_pistol', label = '瓦尔特P99', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_pistol.png', unique = true, useable = false, description = '一款设计为单手持有的小型火器' },
    weapon_pistol_mk2            = { name = 'weapon_pistol_mk2', label = '手枪Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_pistol_mk2.png', unique = true, useable = false, description = '一款升级版的小型火器，设计为单手持有' },
    weapon_combatpistol          = { name = 'weapon_combatpistol', label = '战斗手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_combatpistol.png', unique = true, useable = false, description = '战斗型小型火器，设计为单手持有' },
    weapon_appistol              = { name = 'weapon_appistol', label = 'AP手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_appistol.png', unique = true, useable = false, description = '一款小型自动火器，设计为单手持有' },
    weapon_stungun               = { name = 'weapon_stungun', label = '电击枪', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_stungun.png', unique = true, useable = false, description = '一款发射附有电池线的钩刺的武器，造成短暂麻痹' },
    weapon_pistol50              = { name = 'weapon_pistol50', label = '.50手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_pistol50.png', unique = true, useable = false, description = '一款.50口径的火器，设计为双手持有' },
    weapon_snspistol             = { name = 'weapon_snspistol', label = 'SNS手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_snspistol.png', unique = true, useable = false, description = '一款非常小型的火器，易于隐藏' },
    weapon_heavypistol           = { name = 'weapon_heavypistol', label = '重型手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_heavypistol.png', unique = true, useable = false, description = '一款较重的火器，设计为单手持有（或尝试单手持有）' },
    weapon_vintagepistol         = { name = 'weapon_vintagepistol', label = '复古手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_vintagepistol.png', unique = true, useable = false, description = '一款古董火器，设计为单手持有' },
    weapon_flaregun              = { name = 'weapon_flaregun', label = '信号枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_FLARE', image = 'weapon_flaregun.png', unique = true, useable = false, description = '用于发射信号火箭的手枪' },
    weapon_marksmanpistol        = { name = 'weapon_marksmanpistol', label = '神射手手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_marksmanpistol.png', unique = true, useable = false, description = '一款非常精准的小型火器，设计为单手持有' },
    weapon_revolver              = { name = 'weapon_revolver', label = '左轮手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_revolver.png', unique = true, useable = false, description = '一种具有旋转弹膛的手枪，可多次射击而无需重新装填' },
    weapon_revolver_mk2          = { name = 'weapon_revolver_mk2', label = '暴力左轮', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_revolver_mk2.png', unique = true, useable = true, description = '暴力左轮手枪' },
    weapon_doubleaction          = { name = 'weapon_doubleaction', label = '双动左轮手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_doubleaction.png', unique = true, useable = true, description = '双动左轮手枪' },
    weapon_snspistol_mk2         = { name = 'weapon_snspistol_mk2', label = 'SNS手枪Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_snspistol_mk2.png', unique = true, useable = true, description = 'SNS手枪Mk II' },
    weapon_raypistol             = { name = 'weapon_raypistol', label = '原子射线手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_raypistol.png', unique = true, useable = true, description = '原子射线手枪' },
    weapon_ceramicpistol         = { name = 'weapon_ceramicpistol', label = '陶瓷手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_ceramicpistol.png', unique = true, useable = true, description = '陶瓷手枪' },
    weapon_navyrevolver          = { name = 'weapon_navyrevolver', label = '海军左轮手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_navyrevolver.png', unique = true, useable = true, description = '海军左轮手枪' },
    weapon_gadgetpistol          = { name = 'weapon_gadgetpistol', label = '佩里科手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_gadgetpistol.png', unique = true, useable = true, description = '佩里科手枪' },
    weapon_pistolxm3             = { name = 'weapon_pistolxm3', label = 'XM3手枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_pistolxm3.png', unique = true, useable = true, description = 'XM3手枪' },

    -- 冲锋枪
    weapon_microsmg              = { name = 'weapon_microsmg', label = '微型冲锋枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_microsmg.png', unique = true, useable = false, description = '一款手持轻型冲锋枪' },
    weapon_smg                   = { name = 'weapon_smg', label = '冲锋枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_smg.png', unique = true, useable = false, description = '一款手持轻型冲锋枪' },
    weapon_smg_mk2               = { name = 'weapon_smg_mk2', label = '冲锋枪 Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_smg_mk2.png', unique = true, useable = true, description = '冲锋枪 Mk2' },
    weapon_assaultsmg            = { name = 'weapon_assaultsmg', label = '突击冲锋枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_assaultsmg.png', unique = true, useable = false, description = '一种突击版手持轻型冲锋枪' },
    weapon_combatpdw             = { name = 'weapon_combatpdw', label = '战斗个人防卫武器', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_combatpdw.png', unique = true, useable = false, description = '战斗版手持轻型冲锋枪' },
    weapon_machinepistol         = { name = 'weapon_machinepistol', label = 'Tec-9', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_machinepistol.png', unique = true, useable = false, description = '一款可以进行爆发或全自动射击的自装填手枪' },
    weapon_minismg               = { name = 'weapon_minismg', label = '迷你冲锋枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_minismg.png', unique = true, useable = false, description = '一款迷你型手持轻型冲锋枪' },
    weapon_raycarbine            = { name = 'weapon_raycarbine', label = '不圣地地狱使者', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_raycarbine.png', unique = true, useable = true, description = '雷射卡宾枪' },

    -- 疾风枪
    weapon_pumpshotgun           = { name = 'weapon_pumpshotgun', label = '泵动式霰弹枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_pumpshotgun.png', unique = true, useable = false, description = '一款泵动式滑膛枪，用于近距离发射小型弹丸' },
    weapon_sawnoffshotgun        = { name = 'weapon_sawnoffshotgun', label = '锯短霰弹枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_sawnoffshotgun.png', unique = true, useable = false, description = '一款锯短滑膛枪，用于近距离发射小型弹丸' },
    weapon_assaultshotgun        = { name = 'weapon_assaultshotgun', label = '突击霰弹枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_assaultshotgun.png', unique = true, useable = false, description = '一种突击版滑膛枪，用于近距离发射小型弹丸' },
    weapon_bullpupshotgun        = { name = 'weapon_bullpupshotgun', label = 'Bullpup霰弹枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_bullpupshotgun.png', unique = true, useable = false, description = '一款紧凑型滑膛枪，用于近距离发射小型弹丸' },
    weapon_musket                = { name = 'weapon_musket', label = '火枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_musket.png', unique = true, useable = false, description = '一款步兵用的轻型火枪，通常为滑膛式、火药装填、肩射' },
    weapon_heavyshotgun          = { name = 'weapon_heavyshotgun', label = '重型霰弹枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_heavyshotgun.png', unique = true, useable = false, description = '一款大型滑膛枪，用于近距离发射小型弹丸' },
    weapon_dbshotgun             = { name = 'weapon_dbshotgun', label = '双管霰弹枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_dbshotgun.png', unique = true, useable = false, description = '一款具有两个平行枪管的霰弹枪，能够快速发射两发子弹' },
    weapon_autoshotgun           = { name = 'weapon_autoshotgun', label = '自动霰弹枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_autoshotgun.png', unique = true, useable = false, description = '一款能够进行快速连续射击的霰弹枪' },
    weapon_pumpshotgun_mk2       = { name = 'weapon_pumpshotgun_mk2', label = '泵动霰弹枪 Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_pumpshotgun_mk2.png', unique = true, useable = true, description = '泵动霰弹枪 MK2' },
    weapon_combatshotgun         = { name = 'weapon_combatshotgun', label = '战斗霰弹枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_combatshotgun.png', unique = true, useable = true, description = '战斗霰弹枪' },

    -- 突击步枪
    weapon_assaultrifle          = { name = 'weapon_assaultrifle', label = '突击步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_assaultrifle.png', unique = true, useable = false, description = '一款为步兵设计的自动步枪，具有快速射击和弹匣供弹的特点' },
    weapon_assaultrifle_mk2      = { name = 'weapon_assaultrifle_mk2', label = '突击步枪 Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_assaultrifle_mk2.png', unique = true, useable = true, description = '突击步枪 MK2' },
    weapon_carbinerifle          = { name = 'weapon_carbinerifle', label = '卡宾步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_carbinerifle.png', unique = true, useable = false, description = '一款轻型自动步枪' },
    weapon_carbinerifle_mk2      = { name = 'weapon_carbinerifle_mk2', label = '卡宾步枪 Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_carbinerifle_mk2.png', unique = true, useable = true, description = '卡宾步枪 MK2' },
    weapon_advancedrifle         = { name = 'weapon_advancedrifle', label = '先进步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_advancedrifle.png', unique = true, useable = false, description = '一种突击型自动步枪，设计用于步兵作战' },
    weapon_specialcarbine        = { name = 'weapon_specialcarbine', label = '特种卡宾枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_specialcarbine.png', unique = true, useable = false, description = '一款在各种战斗情况下都非常实用的突击步枪' },
    weapon_bullpuprifle          = { name = 'weapon_bullpuprifle', label = '牛头步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_bullpuprifle.png', unique = true, useable = false, description = '一款紧凑型自动步枪' },
    weapon_compactrifle          = { name = 'weapon_compactrifle', label = '紧凑步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_compactrifle.png', unique = true, useable = false, description = '一种紧凑型的突击步枪' },
    weapon_specialcarbine_mk2    = { name = 'weapon_specialcarbine_mk2', label = '特种卡宾枪 Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_specialcarbine_mk2.png', unique = true, useable = true, description = '特种卡宾枪 MK2' },
    weapon_bullpuprifle_mk2      = { name = 'weapon_bullpuprifle_mk2', label = '牛头步枪 Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_bullpuprifle_mk2.png', unique = true, useable = true, description = '牛头步枪 MK2' },
    weapon_militaryrifle         = { name = 'weapon_militaryrifle', label = '军用步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_militaryrifle.png', unique = true, useable = true, description = '军用步枪' },

    -- 轻机枪
    weapon_mg                    = { name = 'weapon_mg', label = '机枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', image = 'weapon_mg.png', unique = true, useable = false, description = '一种自动武器，可以持续快速射击，只要保持扣动扳机' },
    weapon_combatmg              = { name = 'weapon_combatmg', label = '战斗机枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', image = 'weapon_combatmg.png', unique = true, useable = false, description = '一种自动武器，可以持续快速射击，只要保持扣动扳机，适用于战斗' },
    weapon_gusenberg             = { name = 'weapon_gusenberg', label = '汤普森冲锋枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', image = 'weapon_gusenberg.png', unique = true, useable = false, description = '一种自动步枪，通常被称为汤米枪' },
    weapon_combatmg_mk2          = { name = 'weapon_combatmg_mk2', label = '战斗机枪 Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', image = 'weapon_combatmg_mk2.png', unique = true, useable = true, description = '战斗机枪 MK2' },

    -- 狙击步枪
    weapon_sniperrifle           = { name = 'weapon_sniperrifle', label = '狙击步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_sniperrifle.png', unique = true, useable = false, description = '一款高精度的长距离步枪' },
    weapon_heavysniper           = { name = 'weapon_heavysniper', label = '重型狙击步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_heavysniper.png', unique = true, useable = false, description = '一款升级版的高精度长距离步枪' },
    weapon_marksmanrifle         = { name = 'weapon_marksmanrifle', label = '标枪步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_marksmanrifle.png', unique = true, useable = false, description = '一款非常精准的单发步枪' },
    weapon_remotesniper          = { name = 'weapon_remotesniper', label = '遥控狙击步枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER_REMOTE', image = 'weapon_remotesniper.png', unique = true, useable = false, description = '一种便携式高精度长距离狙击步枪' },
    weapon_heavysniper_mk2       = { name = 'weapon_heavysniper_mk2', label = '重型狙击步枪 Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_heavysniper_mk2.png', unique = true, useable = true, description = '重型狙击步枪 MK2' },
    weapon_marksmanrifle_mk2     = { name = 'weapon_marksmanrifle_mk2', label = '标枪步枪 Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_marksmanrifle_mk2.png', unique = true, useable = true, description = '标枪步枪 MK2' },

    -- 重型武器
    weapon_rpg                   = { name = 'weapon_rpg', label = '火箭筒', weight = 1000, type = 'weapon', ammotype = 'AMMO_RPG', image = 'weapon_rpg.png', unique = true, useable = false, description = '一种火箭推进的手榴弹发射器' },
    weapon_grenadelauncher       = { name = 'weapon_grenadelauncher', label = '榴弹发射器', weight = 1000, type = 'weapon', ammotype = 'AMMO_GRENADELAUNCHER', image = 'weapon_grenadelauncher.png', unique = true, useable = false, description = '一种发射专门设计的大口径弹药的武器，通常带有爆炸、烟雾或毒气战斗部' },
    weapon_grenadelauncher_smoke = { name = 'weapon_grenadelauncher_smoke', label = '烟雾榴弹发射器', weight = 1000, type = 'weapon', ammotype = 'AMMO_GRENADELAUNCHER', image = 'weapon_smokegrenade.png', unique = true, useable = false, description = '一种爆炸时产生大量烟雾的炸弹' },
    weapon_minigun               = { name = 'weapon_minigun', label = '迷你枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_MINIGUN', image = 'weapon_minigun.png', unique = true, useable = false, description = '一种便携式机枪，拥有六根旋转枪管，能以每分钟6,000发的可变射速开火' },
    weapon_firework              = { name = 'weapon_firework', label = '烟花发射器', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_firework.png', unique = true, useable = false, description = '一种包含火药和其他可燃化学物质的装置，点燃后会产生壮观的爆炸' },
    weapon_railgun               = { name = 'weapon_railgun', label = '轨道炮', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_railgun.png', unique = true, useable = false, description = '一种利用电磁力发射高速弹丸的武器' },
    weapon_railgunxm3            = { name = 'weapon_railgunxm3', label = '轨道炮XM3', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_railgunxm3.png', unique = true, useable = false, description = '一种利用电磁力发射高速弹丸的武器' },
    weapon_hominglauncher        = { name = 'weapon_hominglauncher', label = '制导发射器', weight = 1000, type = 'weapon', ammotype = 'AMMO_STINGER', image = 'weapon_hominglauncher.png', unique = true, useable = false, description = '一种装备有电子设备的武器，能够找到并击中目标' },
    weapon_compactlauncher       = { name = 'weapon_compactlauncher', label = '紧凑型发射器', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_compactlauncher.png', unique = true, useable = false, description = '一种紧凑型的榴弹发射器' },
    weapon_rayminigun            = { name = 'weapon_rayminigun', label = '寡妇制造者', weight = 1000, type = 'weapon', ammotype = 'AMMO_MINIGUN', image = 'weapon_rayminigun.png', unique = true, useable = true, description = '武器 Rayminigun' },

    -- 投掷武器
    weapon_grenade               = { name = 'weapon_grenade', label = '手榴弹', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_grenade.png', unique = true, useable = false, description = '一种手持可投掷的炸弹' },
    weapon_bzgas                 = { name = 'weapon_bzgas', label = 'BZ气体', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_bzgas.png', unique = true, useable = false, description = '一种可引起剧烈疼痛的气体罐' },
    weapon_molotov               = { name = 'weapon_molotov', label = '莫洛托夫 cocktail', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_molotov.png', unique = true, useable = false, description = '一种由装有可燃液体的瓶子和点火引线组成的简易炸弹' },
    weapon_stickybomb            = { name = 'weapon_stickybomb', label = 'C4炸弹', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_stickybomb.png', unique = true, useable = false, description = '一种具有粘性的炸弹，投掷后能粘附在物体上直到爆炸' },
    weapon_proxmine              = { name = 'weapon_proxmine', label = '地雷', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_proximitymine.png', unique = true, useable = false, description = '一种放置在地面上的炸弹，接近时会引爆' },
    weapon_snowball              = { name = 'weapon_snowball', label = '雪球', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_snowball.png', unique = true, useable = false, description = '一种由紧压的雪制成的球，通常用于互相投掷' },
    weapon_pipebomb              = { name = 'weapon_pipebomb', label = '管道炸弹', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_pipebomb.png', unique = true, useable = false, description = '一种自制炸弹，其组件被放入管道内' },
    weapon_ball                  = { name = 'weapon_ball', label = '球', weight = 1000, type = 'weapon', ammotype = 'AMMO_BALL', image = 'weapon_ball.png', unique = true, useable = false, description = '一种固体或空心的球形或蛋形物体，用于踢、投或打' },
    weapon_smokegrenade          = { name = 'weapon_smokegrenade', label = '烟雾手榴弹', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_c4.png', unique = true, useable = false, description = '一种能够产生烟雾的爆炸物' },
    weapon_flare                 = { name = 'weapon_flare', label = '信号枪', weight = 1000, type = 'weapon', ammotype = 'AMMO_FLARE', image = 'weapon_flare.png', unique = true, useable = false, description = '一种小型烟火装置，用于照明和信号传递' },

    -- 杂项
    weapon_petrolcan             = { name = 'weapon_petrolcan', label = '油罐', weight = 1000, type = 'weapon', ammotype = 'AMMO_PETROLCAN', image = 'weapon_petrolcan.png', unique = true, useable = false, description = '一种由压制钢板制成的坚固液体容器' },
    weapon_fireextinguisher      = { name = 'weapon_fireextinguisher', label = '灭火器', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_fireextinguisher.png', unique = true, useable = false, description = '一种便携式装置，通过喷射水、泡沫、气体或其他材料来扑灭火灾' },
    weapon_hazardcan             = { name = 'weapon_hazardcan', label = '危险油桶', weight = 1000, type = 'weapon', ammotype = 'AMMO_PETROLCAN', image = 'weapon_hazardcan.png', unique = true, useable = true, description = '危险油桶武器' },

    -- 武器附件
    clip_attachment              = { name = 'clip_attachment', label = '弹匣', weight = 1000, type = 'item', image = 'clip_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的弹匣' },
    drum_attachment              = { name = 'drum_attachment', label = '鼓形弹匣', weight = 1000, type = 'item', image = 'drum_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的鼓形弹匣' },
    flashlight_attachment        = { name = 'flashlight_attachment', label = '手电筒', weight = 1000, type = 'item', image = 'flashlight_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的手电筒' },
    suppressor_attachment        = { name = 'suppressor_attachment', label = '消音器', weight = 1000, type = 'item', image = 'suppressor_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的消音器' },
    smallscope_attachment        = { name = 'smallscope_attachment', label = '小型瞄准镜', weight = 1000, type = 'item', image = 'smallscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的小型瞄准镜' },
    medscope_attachment          = { name = 'medscope_attachment', label = '中型瞄准镜', weight = 1000, type = 'item', image = 'medscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的中型瞄准镜' },
    largescope_attachment        = { name = 'largescope_attachment', label = '大型瞄准镜', weight = 1000, type = 'item', image = 'largescope_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的大型瞄准镜' },
    holoscope_attachment         = { name = 'holoscope_attachment', label = '全息瞄准镜', weight = 1000, type = 'item', image = 'holoscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的全息瞄准镜' },
    advscope_attachment          = { name = 'advscope_attachment', label = '高级瞄准镜', weight = 1000, type = 'item', image = 'advscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的高级瞄准镜' },
    nvscope_attachment           = { name = 'nvscope_attachment', label = '夜视瞄准镜', weight = 1000, type = 'item', image = 'nvscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的夜视瞄准镜' },
    thermalscope_attachment      = { name = 'thermalscope_attachment', label = '热成像瞄准镜', weight = 1000, type = 'item', image = 'thermalscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的热成像瞄准镜' },
    flat_muzzle_brake            = { name = 'flat_muzzle_brake', label = '平面消焰器', weight = 1000, type = 'item', image = 'flat_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '用于武器的消焰器' },
    tactical_muzzle_brake        = { name = 'tactical_muzzle_brake', label = '战术消焰器', weight = 1000, type = 'item', image = 'tactical_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '用于武器的战术消焰器' },
    fat_end_muzzle_brake         = { name = 'fat_end_muzzle_brake', label = '粗端消焰器', weight = 1000, type = 'item', image = 'fat_end_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '用于武器的粗端消焰器' },
    precision_muzzle_brake       = { name = 'precision_muzzle_brake', label = '精准消焰器', weight = 1000, type = 'item', image = 'precision_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '用于武器的精准消焰器' },
    heavy_duty_muzzle_brake      = { name = 'heavy_duty_muzzle_brake', label = '重型消焰器', weight = 1000, type = 'item', image = 'heavy_duty_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '用于武器的重型消焰器' },
    slanted_muzzle_brake         = { name = 'slanted_muzzle_brake', label = '斜角消焰器', weight = 1000, type = 'item', image = 'slanted_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '用于武器的斜角消焰器' },
    split_end_muzzle_brake       = { name = 'split_end_muzzle_brake', label = '分体消焰器', weight = 1000, type = 'item', image = 'split_end_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '用于武器的分体消焰器' },
    squared_muzzle_brake         = { name = 'squared_muzzle_brake', label = '方形消焰器', weight = 1000, type = 'item', image = 'squared_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '用于武器的方形消焰器' },
    bellend_muzzle_brake         = { name = 'bellend_muzzle_brake', label = '铃形消焰器', weight = 1000, type = 'item', image = 'bellend_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '用于武器的铃形消焰器' },
    barrel_attachment            = { name = 'barrel_attachment', label = '枪管', weight = 1000, type = 'item', image = 'barrel_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的枪管' },
    grip_attachment              = { name = 'grip_attachment', label = '握把', weight = 1000, type = 'item', image = 'grip_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的握把' },
    comp_attachment              = { name = 'comp_attachment', label = '补偿器', weight = 1000, type = 'item', image = 'comp_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的补偿器' },
    luxuryfinish_attachment      = { name = 'luxuryfinish_attachment', label = '奢华外观', weight = 1000, type = 'item', image = 'luxuryfinish_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的奢华外观' },
    digicamo_attachment          = { name = 'digicamo_attachment', label = '数字迷彩', weight = 1000, type = 'item', image = 'digicamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的数字迷彩' },
    brushcamo_attachment         = { name = 'brushcamo_attachment', label = '笔触迷彩', weight = 1000, type = 'item', image = 'brushcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的笔触迷彩' },
    woodcamo_attachment          = { name = 'woodcamo_attachment', label = '丛林迷彩', weight = 1000, type = 'item', image = 'woodcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '用于武器的丛林迷彩' },
    skullcamo_attachment         = { name = 'skullcamo_attachment', label = '骷髅迷彩', weight = 1000, type = 'item', image = 'skullcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '骷髅哦~~~' },
    sessantacamo_attachment      = { name = 'sessantacamo_attachment', label = '六十六迷彩', weight = 1000, type = 'item', image = 'sessantacamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '一款适用于武器的六十六迷彩' },
    perseuscamo_attachment       = { name = 'perseuscamo_attachment', label = '海神迷彩', weight = 1000, type = 'item', image = 'perseuscamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '一款适用于武器的海神迷彩' },
    leopardcamo_attachment       = { name = 'leopardcamo_attachment', label = '豹纹迷彩', weight = 1000, type = 'item', image = 'leopardcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '一款适用于武器的豹纹迷彩' },
    zebracamo_attachment         = { name = 'zebracamo_attachment', label = '斑马迷彩', weight = 1000, type = 'item', image = 'zebracamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '一款适用于武器的斑马迷彩' },
    geocamo_attachment           = { name = 'geocamo_attachment', label = '几何迷彩', weight = 1000, type = 'item', image = 'geocamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '一款适用于武器的几何迷彩' },
    boomcamo_attachment          = { name = 'boomcamo_attachment', label = '爆炸迷彩', weight = 1000, type = 'item', image = 'boomcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '一款适用于武器的爆炸迷彩' },
    patriotcamo_attachment       = { name = 'patriotcamo_attachment', label = '爱国迷彩', weight = 1000, type = 'item', image = 'patriotcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '一款适用于武器的爱国迷彩' },
    
    -- 武器涂装
    weapontint_0                 = { name = 'weapontint_0', label = '默认涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '默认/黑色武器涂装' },
    weapontint_1                 = { name = 'weapontint_1', label = '绿色涂装', weight = 1000, type = 'item', image = 'weapontint_green.png', unique = false, useable = true, shouldClose = true, description = '绿色武器涂装' },
    weapontint_2                 = { name = 'weapontint_2', label = '金色涂装', weight = 1000, type = 'item', image = 'weapontint_gold.png', unique = false, useable = true, shouldClose = true, description = '金色武器涂装' },
    weapontint_3                 = { name = 'weapontint_3', label = '粉色涂装', weight = 1000, type = 'item', image = 'weapontint_pink.png', unique = false, useable = true, shouldClose = true, description = '粉色武器涂装' },
    weapontint_4                 = { name = 'weapontint_4', label = '军用涂装', weight = 1000, type = 'item', image = 'weapontint_army.png', unique = false, useable = true, shouldClose = true, description = '军用武器涂装' },
    weapontint_5                 = { name = 'weapontint_5', label = 'LSPD涂装', weight = 1000, type = 'item', image = 'weapontint_lspd.png', unique = false, useable = true, shouldClose = true, description = 'LSPD武器涂装' },
    weapontint_6                 = { name = 'weapontint_6', label = '橙色涂装', weight = 1000, type = 'item', image = 'weapontint_orange.png', unique = false, useable = true, shouldClose = true, description = '橙色武器涂装' },
    weapontint_7                 = { name = 'weapontint_7', label = '铂金涂装', weight = 1000, type = 'item', image = 'weapontint_plat.png', unique = false, useable = true, shouldClose = true, description = '铂金武器涂装' },
    weapontint_mk2_0             = { name = 'weapontint_mk2_0', label = '经典黑色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的经典黑色涂装' },
    weapontint_mk2_1             = { name = 'weapontint_mk2_1', label = '经典灰色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的经典灰色涂装' },
    weapontint_mk2_2             = { name = 'weapontint_mk2_2', label = '经典双色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的经典双色涂装' },
    weapontint_mk2_3             = { name = 'weapontint_mk2_3', label = '经典白色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的经典白色涂装' },
    weapontint_mk2_4             = { name = 'weapontint_mk2_4', label = '经典米色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的经典米色涂装' },
    weapontint_mk2_5             = { name = 'weapontint_mk2_5', label = '经典绿色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的经典绿色涂装' },
    weapontint_mk2_6             = { name = 'weapontint_mk2_6', label = '经典蓝色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的经典蓝色涂装' },
    weapontint_mk2_7             = { name = 'weapontint_mk2_7', label = '经典地球色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的经典地球色涂装' },
    weapontint_mk2_8             = { name = 'weapontint_mk2_8', label = '经典棕黑色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的经典棕黑色涂装' },
    weapontint_mk2_9             = { name = 'weapontint_mk2_9', label = '红色对比涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的红色对比涂装' },
    weapontint_mk2_10            = { name = 'weapontint_mk2_10', label = '蓝色对比涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的蓝色对比涂装' },
    weapontint_mk2_11            = { name = 'weapontint_mk2_11', label = '黄色对比涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的黄色对比涂装' },
    weapontint_mk2_12            = { name = 'weapontint_mk2_12', label = '橙色对比涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的橙色对比涂装' },
    weapontint_mk2_13            = { name = 'weapontint_mk2_13', label = '大胆粉色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的大胆粉色涂装' },
    weapontint_mk2_14            = { name = 'weapontint_mk2_14', label = '大胆紫黄涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的大胆紫黄涂装' },
    weapontint_mk2_15            = { name = 'weapontint_mk2_15', label = '大胆橙色涂装', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '适用于MK2武器的大胆橙色涂装' },
    weapontint_mk2_16            = { name = 'weapontint_mk2_16', label = '粗犷的绿色和紫色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的粗犷绿色和紫色武器染色' },
    weapontint_mk2_17            = { name = 'weapontint_mk2_17', label = '粗犷的红色特征染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的粗犷红色特征武器染色' },
    weapontint_mk2_18            = { name = 'weapontint_mk2_18', label = '粗犷的绿色特征染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的粗犷绿色特征武器染色' },
    weapontint_mk2_19            = { name = 'weapontint_mk2_19', label = '粗犷的青色特征染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的粗犷青色特征武器染色' },
    weapontint_mk2_20            = { name = 'weapontint_mk2_20', label = '粗犷的黄色特征染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的粗犷黄色特征武器染色' },
    weapontint_mk2_21            = { name = 'weapontint_mk2_21', label = '粗犷的红色和白色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的粗犷红色和白色武器染色' },
    weapontint_mk2_22            = { name = 'weapontint_mk2_22', label = '粗犷的蓝色和白色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的粗犷蓝色和白色武器染色' },
    weapontint_mk2_23            = { name = 'weapontint_mk2_23', label = '金属金色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属金色武器染色' },
    weapontint_mk2_24            = { name = 'weapontint_mk2_24', label = '金属铂金色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属铂金色武器染色' },
    weapontint_mk2_25            = { name = 'weapontint_mk2_25', label = '金属灰色和淡紫色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属灰色和淡紫色武器染色' },
    weapontint_mk2_26            = { name = 'weapontint_mk2_26', label = '金属紫色和青柠色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属紫色和青柠色武器染色' },
    weapontint_mk2_27            = { name = 'weapontint_mk2_27', label = '金属红色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属红色武器染色' },
    weapontint_mk2_28            = { name = 'weapontint_mk2_28', label = '金属绿色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属绿色武器染色' },
    weapontint_mk2_29            = { name = 'weapontint_mk2_29', label = '金属蓝色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属蓝色武器染色' },
    weapontint_mk2_30            = { name = 'weapontint_mk2_30', label = '金属白色和水绿色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属白色和水绿色武器染色' },
    weapontint_mk2_31            = { name = 'weapontint_mk2_31', label = '金属橙色和黄色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属橙色和黄色武器染色' },
    weapontint_mk2_32            = { name = 'weapontint_mk2_32', label = '金属红色和黄色染色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = '用于 MK2 武器的金属红色和黄色武器染色' },
    
    -- 物品
    -- 弹药
    pistol_ammo                  = { name = 'pistol_ammo', label = '手枪弹药', weight = 200, type = 'item', image = 'pistol_ammo.png', unique = false, useable = true, shouldClose = true, description = '用于手枪的弹药' },
    rifle_ammo                   = { name = 'rifle_ammo', label = '步枪弹药', weight = 1000, type = 'item', image = 'rifle_ammo.png', unique = false, useable = true, shouldClose = true, description = '用于步枪的弹药' },
    smg_ammo                     = { name = 'smg_ammo', label = '冲锋枪弹药', weight = 500, type = 'item', image = 'smg_ammo.png', unique = false, useable = true, shouldClose = true, description = '用于冲锋枪的弹药' },
    shotgun_ammo                 = { name = 'shotgun_ammo', label = '霰弹枪弹药', weight = 500, type = 'item', image = 'shotgun_ammo.png', unique = false, useable = true, shouldClose = true, description = '用于霰弹枪的弹药' },
    mg_ammo                      = { name = 'mg_ammo', label = '机枪弹药', weight = 1000, type = 'item', image = 'mg_ammo.png', unique = false, useable = true, shouldClose = true, description = '用于机枪的弹药' },
    snp_ammo                     = { name = 'snp_ammo', label = '狙击枪弹药', weight = 1000, type = 'item', image = 'rifle_ammo.png', unique = false, useable = true, shouldClose = true, description = '用于狙击枪的弹药' },
    emp_ammo                     = { name = 'emp_ammo', label = 'EMP弹药', weight = 200, type = 'item', image = 'emp_ammo.png', unique = false, useable = true, shouldClose = true, description = '用于EMP发射器的弹药' },

    -- 卡片
    id_card                      = { name = 'id_card', label = '身份证', weight = 0, type = 'item', image = 'id_card.png', unique = true, useable = true, shouldClose = false, description = '包含所有个人信息的卡片，用于身份识别' },
    driver_license               = { name = 'driver_license', label = '驾驶证', weight = 0, type = 'item', image = 'driver_license.png', unique = true, useable = true, shouldClose = false, description = '证明你可以驾驶车辆的许可证' },
    lawyerpass                   = { name = 'lawyerpass', label = '律师通行证', weight = 0, type = 'item', image = 'lawyerpass.png', unique = true, useable = true, shouldClose = false, description = '仅限律师使用的通行证，表明他们可以代表嫌疑人' },
    weaponlicense                = { name = 'weaponlicense', label = '武器许可证', weight = 0, type = 'item', image = 'weapon_license.png', unique = true, useable = true, shouldClose = true, description = '武器许可证' },
    bank_card                    = { name = 'bank_card', label = '银行卡', weight = 0, type = 'item', image = 'bank_card.png', unique = true, useable = true, shouldClose = true, description = '用于访问ATM的卡片' },
    security_card_01             = { name = 'security_card_01', label = '安全卡 A', weight = 0, type = 'item', image = 'security_card_01.png', unique = false, useable = true, shouldClose = true, description = '一张安全卡...我想知道它通向哪里' },
    security_card_02             = { name = 'security_card_02', label = '安全卡 B', weight = 0, type = 'item', image = 'security_card_02.png', unique = false, useable = true, shouldClose = true, description = '一张安全卡...我想知道它通向哪里' },

    -- 食物
    tosti                        = { name = 'tosti', label = '烤奶酪三明治', weight = 200, type = 'item', image = 'tosti.png', unique = false, useable = true, shouldClose = true, description = '很好吃的食物' },
    twerks_candy                 = { name = 'twerks_candy', label = 'Twerks糖果', weight = 100, type = 'item', image = 'twerks_candy.png', unique = false, useable = true, shouldClose = true, description = '美味的糖果 :O' },
    snikkel_candy                = { name = 'snikkel_candy', label = 'Snikkel糖果', weight = 100, type = 'item', image = 'snikkel_candy.png', unique = false, useable = true, shouldClose = true, description = '美味的糖果 :O' },
    sandwich                     = { name = 'sandwich', label = '三明治', weight = 200, type = 'item', image = 'sandwich.png', unique = false, useable = true, shouldClose = true, description = '好吃的面包，适合你的胃' },

    -- 饮料
    water_bottle                 = { name = 'water_bottle', label = '水瓶', weight = 500, type = 'item', image = 'water_bottle.png', unique = false, useable = true, shouldClose = true, description = '给所有口渴的人' },
    coffee                       = { name = 'coffee', label = '咖啡', weight = 200, type = 'item', image = 'coffee.png', unique = false, useable = true, shouldClose = true, description = '给自己加点咖啡因' },
    kurkakola                    = { name = 'kurkakola', label = '可乐', weight = 500, type = 'item', image = 'cola.png', unique = false, useable = true, shouldClose = true, description = '给所有口渴的人' },

    -- 酒
    beer                         = { name = 'beer', label = '啤酒', weight = 500, type = 'item', image = 'beer.png', unique = false, useable = true, shouldClose = true, description = '没有什么比一瓶冷啤酒更好的了！' },
    whiskey                      = { name = 'whiskey', label = '威士忌', weight = 500, type = 'item', image = 'whiskey.png', unique = false, useable = true, shouldClose = true, description = '给所有口渴的人' },
    vodka                        = { name = 'vodka', label = '伏特加', weight = 500, type = 'item', image = 'vodka.png', unique = false, useable = true, shouldClose = true, description = '给所有口渴的人' },
    grape                        = { name = 'grape', label = '葡萄', weight = 100, type = 'item', image = 'grape.png', unique = false, useable = true, shouldClose = false, description = '嗯，美味的葡萄' },
    wine                         = { name = 'wine', label = '葡萄酒', weight = 300, type = 'item', image = 'wine.png', unique = false, useable = true, shouldClose = false, description = '在一个美好的夜晚享受一杯好酒' },
    grapejuice                   = { name = 'grapejuice', label = '葡萄汁', weight = 200, type = 'item', image = 'grapejuice.png', unique = false, useable = true, shouldClose = false, description = '葡萄汁被认为对健康有益' },

    -- 毒品
    joint                        = { name = 'joint', label = '大麻烟', weight = 0, type = 'item', image = 'joint.png', unique = false, useable = true, shouldClose = true, description = 'Sidney 会为你感到骄傲' },
    cokebaggy                    = { name = 'cokebaggy', label = '可卡因袋', weight = 0, type = 'item', image = 'cocaine_baggy.png', unique = false, useable = true, shouldClose = true, description = '快速让你高兴起来' },
    crack_baggy                  = { name = 'crack_baggy', label = '裂解可卡因袋', weight = 0, type = 'item', image = 'crack_baggy.png', unique = false, useable = true, shouldClose = true, description = '让你更快高兴起来' },
    xtcbaggy                     = { name = 'xtcbaggy', label = '摇头丸袋', weight = 0, type = 'item', image = 'xtc_baggy.png', unique = false, useable = true, shouldClose = true, description = '吃下这些药丸吧' },
    coke_brick                   = { name = 'coke_brick', label = '可卡因砖', weight = 1000, type = 'item', image = 'coke_brick.png', unique = true, useable = false, shouldClose = true, description = '重的可卡因包，主要用于交易，占用很大空间' },
    weed_brick                   = { name = 'weed_brick', label = '大麻砖', weight = 1000, type = 'item', image = 'weed_brick.png', unique = false, useable = false, shouldClose = true, description = '1公斤的大麻砖，用于向大客户出售' },
    coke_small_brick             = { name = 'coke_small_brick', label = '小可卡因包', weight = 350, type = 'item', image = 'coke_small_brick.png', unique = true, useable = false, shouldClose = true, description = '小型的可卡因包，主要用于交易，占用很大空间' },
    oxy                          = { name = 'oxy', label = '处方奥施康定', weight = 0, type = 'item', image = 'oxy.png', unique = false, useable = true, shouldClose = true, description = '标签已被撕掉' },
    meth                         = { name = 'meth', label = '冰毒', weight = 100, type = 'item', image = 'meth_baggy.png', unique = false, useable = true, shouldClose = true, description = '一袋冰毒' },
    rolling_paper                = { name = 'rolling_paper', label = '卷烟纸', weight = 0, type = 'item', image = 'rolling_paper.png', unique = false, useable = false, shouldClose = true, description = '专门用来包裹和吸烟烟草或大麻的纸' },

    -- Seed And Weed
    weed_whitewidow              = { name = 'weed_whitewidow', label = '白寡妇 2克', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = '著名的大麻品种，以其强烈的精神效应和高产量而闻名。' },
    weed_skunk                   = { name = 'weed_skunk', label = '臭鼬 2克', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = '非常高的THC和CBD含量，强烈且臭味浓烈的大麻品种。' },
    weed_purplehaze              = { name = 'weed_purplehaze', label = '紫色迷雾 2克', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = '闻名全球的经典大麻品种，因其紫色的花朵而得名，伴随有一些艺术感的视觉效果，紫色迷雾通常被认为是适合日间使用的品种。' },
    weed_ogkush                  = { name = 'weed_ogkush', label = 'OG Kush 2克', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = '其复杂的香气（混合了柑橘、松木和香料的味道）和强烈的效果而闻名，它在加州的地下文化中非常受欢迎，是许多混合品种的祖先。' },
    weed_amnesia                 = { name = 'weed_amnesia', label = '健忘 2克', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = '强烈的头脑高涨和精神激励的体验，某些使用者可能会感到精神混乱或短暂的记忆丧失。' },
    weed_ak47                    = { name = 'weed_ak47', label = 'AK47 2克', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = '名字源于著名的“AK-47”突击步枪，具有强烈的效果，因其较高的THC（四氢大麻酚）含量，通常用于放松、减压和治疗目的。' },
    weed_whitewidow_seed         = { name = 'weed_whitewidow_seed', label = '白寡妇种子', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = false, description = '著名的大麻品种，以其强烈的精神效应和高产量而闻名。' },
    weed_skunk_seed              = { name = 'weed_skunk_seed', label = '臭鼬种子', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = '非常高的THC和CBD含量，强烈且臭味浓烈的大麻品种。' },
    weed_purplehaze_seed         = { name = 'weed_purplehaze_seed', label = '紫色迷雾种子', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = '闻名全球的经典大麻品种，因其紫色的花朵而得名，伴随有一些艺术感的视觉效果，紫色迷雾通常被认为是适合日间使用的品种。' },
    weed_ogkush_seed             = { name = 'weed_ogkush_seed', label = 'OG Kush种子', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = '其复杂的香气（混合了柑橘、松木和香料的味道）和强烈的效果而闻名，它在加州的地下文化中非常受欢迎，是许多混合品种的祖先。' },
    weed_amnesia_seed            = { name = 'weed_amnesia_seed', label = '健忘种子', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = '强烈的头脑高涨和精神激励的体验，某些使用者可能会感到精神混乱或短暂的记忆丧失。' },
    weed_ak47_seed               = { name = 'weed_ak47_seed', label = 'AK47种子', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = '名字源于著名的“AK-47”突击步枪，具有强烈的效果，因其较高的THC（四氢大麻酚）含量，通常用于放松、减压和治疗目的。' },
    empty_weed_bag               = { name = 'empty_weed_bag', label = '空大麻袋', weight = 0, type = 'item', image = 'weed_baggy_empty.png', unique = false, useable = true, shouldClose = true, description = '一个小的空袋子' },
    weed_nutrition               = { name = 'weed_nutrition', label = '植物肥料', weight = 2000, type = 'item', image = 'weed_nutrition.png', unique = false, useable = true, shouldClose = true, description = '植物肥料' },

    -- 材料
    plastic                      = { name = 'plastic', label = '塑料', weight = 100, type = 'item', image = 'plastic.png', unique = false, useable = false, shouldClose = false, description = '回收！- Greta Thunberg 2019' },
    metalscrap                   = { name = 'metalscrap', label = '金属废料', weight = 100, type = 'item', image = 'metalscrap.png', unique = false, useable = false, shouldClose = false, description = '你可能可以用它做点什么好东西' },
    copper                       = { name = 'copper', label = '铜', weight = 100, type = 'item', image = 'copper.png', unique = false, useable = false, shouldClose = false, description = '一块不错的金属，可能可以用来做点什么' },
    aluminum                     = { name = 'aluminum', label = '铝', weight = 100, type = 'item', image = 'aluminum.png', unique = false, useable = false, shouldClose = false, description = '一块不错的金属，可能可以用来做点什么' },
    aluminumoxide                = { name = 'aluminumoxide', label = '铝粉', weight = 100, type = 'item', image = 'aluminumoxide.png', unique = false, useable = false, shouldClose = false, description = '一些粉末，可以混合使用' },
    iron                         = { name = 'iron', label = '铁', weight = 100, type = 'item', image = 'iron.png', unique = false, useable = false, shouldClose = false, description = '一块很实用的金属，可能可以用来做点什么' },
    ironoxide                    = { name = 'ironoxide', label = '铁粉', weight = 100, type = 'item', image = 'ironoxide.png', unique = false, useable = false, shouldClose = false, description = '一些粉末，可以混合使用' },
    steel                        = { name = 'steel', label = '钢', weight = 100, type = 'item', image = 'steel.png', unique = false, useable = false, shouldClose = false, description = '一块不错的金属，可能可以用来做点什么' },
    rubber                       = { name = 'rubber', label = '橡胶', weight = 100, type = 'item', image = 'rubber.png', unique = false, useable = false, shouldClose = false, description = '橡胶，我相信你可以用它做个橡胶鸭子 :D' },
    glass                        = { name = 'glass', label = '玻璃', weight = 100, type = 'item', image = 'glass.png', unique = false, useable = false, shouldClose = false, description = '非常脆弱，小心处理' },

    -- 工具
    lockpick                     = { name = 'lockpick', label = '撬锁工具', weight = 300, type = 'item', image = 'lockpick.png', unique = false, useable = true, shouldClose = true, description = '如果你经常丢钥匙，这个非常有用……或者你想用它做点别的事情...' },
    advancedlockpick             = { name = 'advancedlockpick', label = '高级撬锁工具', weight = 500, type = 'item', image = 'advancedlockpick.png', unique = false, useable = true, shouldClose = true, description = '如果你经常丢钥匙，这个非常有用...也可以用来开啤酒' },
    electronickit                = { name = 'electronickit', label = '电子工具包', weight = 100, type = 'item', image = 'electronickit.png', unique = false, useable = true, shouldClose = true, description = '如果你一直想做一个机器人，或许可以从这里开始。也许你会成为下一个Elon Musk？' },
    gatecrack                    = { name = 'gatecrack', label = '门禁破解', weight = 0, type = 'item', image = 'usb_device.png', unique = false, useable = false, shouldClose = true, description = '便捷的软件，可以破解一些门禁' },
    thermite                     = { name = 'thermite', label = '热焰', weight = 1000, type = 'item', image = 'thermite.png', unique = false, useable = true, shouldClose = true, description = '有时候你会希望一切都能燃烧起来' },
    trojan_usb                   = { name = 'trojan_usb', label = '木马U盘', weight = 0, type = 'item', image = 'usb_device.png', unique = false, useable = false, shouldClose = true, description = '便捷的软件，可以关闭一些系统' },
    screwdriverset               = { name = 'screwdriverset', label = '螺丝刀套装', weight = 1000, type = 'item', image = 'screwdriverset.png', unique = false, useable = false, shouldClose = false, description = '非常有用来拧螺丝…' },
    drill                        = { name = 'drill', label = '电钻', weight = 20000, type = 'item', image = 'drill.png', unique = false, useable = false, shouldClose = false, description = '真正的工具...' },

    -- 载具相关
    nitrous                      = { name = 'nitrous', label = '氮气', weight = 1000, type = 'item', image = 'nitrous.png', unique = false, useable = true, shouldClose = true, description = '加速，踩下油门！:D' },
    repairkit                    = { name = 'repairkit', label = '修理包', weight = 2500, type = 'item', image = 'repairkit.png', unique = false, useable = true, shouldClose = true, description = '一套修理工具，修理你的车辆' },
    advancedrepairkit            = { name = 'advancedrepairkit', label = '高级修理包', weight = 4000, type = 'item', image = 'advancedkit.png', unique = false, useable = true, shouldClose = true, description = '一套修理工具，修理你的车辆' },
    cleaningkit                  = { name = 'cleaningkit', label = '清洁工具包', weight = 250, type = 'item', image = 'cleaningkit.png', unique = false, useable = true, shouldClose = true, description = '一块微纤维布和一些肥皂让你的车重新闪亮！' },
    tunerlaptop                  = { name = 'tunerlaptop', label = '调谐芯片', weight = 2000, type = 'item', image = 'tunerchip.png', unique = true, useable = true, shouldClose = true, description = '用这个调谐芯片可以让你的车变得更强……如果你知道自己在做什么的话' },
    harness                      = { name = 'harness', label = '赛车安全带', weight = 1000, type = 'item', image = 'harness.png', unique = true, useable = true, shouldClose = true, description = '赛车安全带，无论发生什么你都能留在车里' },
    jerry_can                    = { name = 'jerry_can', label = '20L油桶', weight = 20000, type = 'item', image = 'jerry_can.png', unique = false, useable = true, shouldClose = true, description = '装满油的油桶' },
    tirerepairkit                = { name = 'tirerepairkit', label = '轮胎修理包', weight = 1000, type = 'item', image = 'tirerepairkit.png', unique = false, useable = true, shouldClose = true, description = '修理轮胎的工具包' },

    -- 机械相关
    veh_toolbox                  = { name = 'veh_toolbox', label = '工具箱', weight = 1000, type = 'item', image = 'veh_toolbox.png', unique = false, useable = true, shouldClose = true, description = '检查车辆状态' },
    veh_armor                    = { name = 'veh_armor', label = '装甲', weight = 1000, type = 'item', image = 'veh_armor.png', unique = false, useable = true, shouldClose = true, description = '升级车辆装甲' },
    veh_brakes                   = { name = 'veh_brakes', label = '刹车', weight = 1000, type = 'item', image = 'veh_brakes.png', unique = false, useable = true, shouldClose = true, description = '升级车辆刹车系统' },
    veh_engine                   = { name = 'veh_engine', label = '引擎', weight = 1000, type = 'item', image = 'veh_engine.png', unique = false, useable = true, shouldClose = true, description = '升级车辆引擎' },
    veh_suspension               = { name = 'veh_suspension', label = '悬挂系统', weight = 1000, type = 'item', image = 'veh_suspension.png', unique = false, useable = true, shouldClose = true, description = '升级车辆悬挂系统' },
    veh_transmission             = { name = 'veh_transmission', label = '变速器', weight = 1000, type = 'item', image = 'veh_transmission.png', unique = false, useable = true, shouldClose = true, description = '升级车辆变速器' },
    veh_turbo                    = { name = 'veh_turbo', label = '涡轮增压器', weight = 1000, type = 'item', image = 'veh_turbo.png', unique = false, useable = true, shouldClose = true, description = '安装涡轮增压器' },
    veh_interior                 = { name = 'veh_interior', label = '车内饰', weight = 1000, type = 'item', image = 'veh_interior.png', unique = false, useable = true, shouldClose = true, description = '升级车辆内饰' },
    veh_exterior                 = { name = 'veh_exterior', label = '车外观', weight = 1000, type = 'item', image = 'veh_exterior.png', unique = false, useable = true, shouldClose = true, description = '升级车辆外观' },
    veh_wheels                   = { name = 'veh_wheels', label = '车轮', weight = 1000, type = 'item', image = 'veh_wheels.png', unique = false, useable = true, shouldClose = true, description = '升级车辆轮胎' },
    veh_neons                    = { name = 'veh_neons', label = '霓虹灯', weight = 1000, type = 'item', image = 'veh_neons.png', unique = false, useable = true, shouldClose = true, description = '升级车辆霓虹灯' },
    veh_xenons                   = { name = 'veh_xenons', label = '氙气灯', weight = 1000, type = 'item', image = 'veh_xenons.png', unique = false, useable = true, shouldClose = true, description = '升级车辆氙气灯' },
    veh_tint                     = { name = 'veh_tint', label = '窗膜', weight = 1000, type = 'item', image = 'veh_tint.png', unique = false, useable = true, shouldClose = true, description = '安装车辆窗膜' },
    veh_plates                   = { name = 'veh_plates', label = '车牌', weight = 1000, type = 'item', image = 'veh_plates.png', unique = false, useable = true, shouldClose = true, description = '安装车辆车牌' },

    -- 医疗物品
    firstaid                     = { name = 'firstaid', label = '急救包', weight = 2500, type = 'item', image = 'firstaid.png', unique = false, useable = true, shouldClose = true, description = '你可以使用这个急救包让别人恢复状态' },
    bandage                      = { name = 'bandage', label = '绷带', weight = 0, type = 'item', image = 'bandage.png', unique = false, useable = true, shouldClose = true, description = '每次都有用的绷带' },
    ifaks                        = { name = 'ifaks', label = 'IFAK急救包', weight = 200, type = 'item', image = 'ifaks.png', unique = false, useable = true, shouldClose = true, description = 'IFAK急救包用于治疗，并能完全缓解压力' },
    painkillers                  = { name = 'painkillers', label = '止痛药', weight = 0, type = 'item', image = 'painkillers.png', unique = false, useable = true, shouldClose = true, description = '对于无法忍受的疼痛，服用这颗药片会让你恢复活力' },
    walkstick                    = { name = 'walkstick', label = '拐杖', weight = 1000, type = 'item', image = 'walkstick.png', unique = false, useable = true, shouldClose = true, description = '给各位老奶奶准备的拐杖.. 哈哈' },

    -- 通信工具
    phone                        = { name = 'phone', label = '手机', weight = 700, type = 'item', image = 'phone.png', unique = true, useable = false, shouldClose = false, description = '你的手机真是太酷了' },
    radio                        = { name = 'radio', label = '无线电', weight = 2000, type = 'item', image = 'radio.png', unique = true, useable = true, shouldClose = true, description = '你可以通过无线电信号与人沟通' },
    iphone                       = { name = 'iphone', label = 'iPhone', weight = 1000, type = 'item', image = 'iphone.png', unique = false, useable = false, shouldClose = true, description = '非常昂贵的手机' },
    samsungphone                 = { name = 'samsungphone', label = '三星S10', weight = 1000, type = 'item', image = 'samsungphone.png', unique = false, useable = false, shouldClose = true, description = '非常昂贵的手机' },
    laptop                       = { name = 'laptop', label = '笔记本电脑', weight = 4000, type = 'item', image = 'laptop.png', unique = false, useable = false, shouldClose = true, description = '昂贵的笔记本电脑' },
    tablet                       = { name = 'tablet', label = '平板电脑', weight = 2000, type = 'item', image = 'tablet.png', unique = false, useable = false, shouldClose = true, description = '昂贵的平板电脑' },
    fitbit                       = { name = 'fitbit', label = 'Fitbit手环', weight = 500, type = 'item', image = 'fitbit.png', unique = true, useable = true, shouldClose = true, description = '我喜欢Fitbit' },
    radioscanner                 = { name = 'radioscanner', label = '无线电扫描仪', weight = 1000, type = 'item', image = 'radioscanner.png', unique = false, useable = false, shouldClose = true, description = '这个可以接收到一些警察的报警信息，但不是百分百有效' },
    pinger                       = { name = 'pinger', label = '定位器', weight = 1000, type = 'item', image = 'pinger.png', unique = false, useable = false, shouldClose = true, description = '通过定位器和你的手机，你可以发送出你的位置信息' },
    cryptostick                  = { name = 'cryptostick', label = '加密货币U盘', weight = 200, type = 'item', image = 'cryptostick.png', unique = true, useable = true, shouldClose = true, description = '为什么有人会购买不存在的货币呢..它会包含多少呢..?' },

    -- 盗窃和珠宝
    rolex                        = { name = 'rolex', label = '金表', weight = 1500, type = 'item', image = 'rolex.png', unique = false, useable = false, shouldClose = true, description = '这块金表看起来像是打 Jackpot 一样！' },
    diamond_ring                 = { name = 'diamond_ring', label = '钻石戒指', weight = 1500, type = 'item', image = 'diamond_ring.png', unique = false, useable = false, shouldClose = true, description = '这枚钻石戒指看起来像是打 Jackpot 一样！' },
    diamond                      = { name = 'diamond', label = '钻石', weight = 1000, type = 'item', image = 'diamond.png', unique = false, useable = false, shouldClose = true, description = '这颗钻石看起来像是打 Jackpot 一样！' },
    goldchain                    = { name = 'goldchain', label = '金链', weight = 1500, type = 'item', image = 'goldchain.png', unique = false, useable = false, shouldClose = true, description = '这条金链看起来像是打 Jackpot 一样！' },
    tenkgoldchain                = { name = 'tenkgoldchain', label = '10k 金链', weight = 2000, type = 'item', image = '10kgoldchain.png', unique = false, useable = false, shouldClose = true, description = '10 克拉金链' },
    goldbar                      = { name = 'goldbar', label = '金条', weight = 7000, type = 'item', image = 'goldbar.png', unique = false, useable = false, shouldClose = true, description = '看起来相当贵重' },

    -- 警察工具
    armor                        = { name = 'armor', label = '护甲', weight = 5000, type = 'item', image = 'armor.png', unique = false, useable = true, shouldClose = true, description = '一些保护不会有坏处…对吧？' },
    heavyarmor                   = { name = 'heavyarmor', label = '重型护甲', weight = 5000, type = 'item', image = 'armor.png', unique = false, useable = true, shouldClose = true, description = '一些保护不会有坏处…对吧？' },
    handcuffs                    = { name = 'handcuffs', label = '手铐', weight = 100, type = 'item', image = 'handcuffs.png', unique = false, useable = true, shouldClose = true, description = '在有人捣乱时派上用场。也许它可以用来做别的事情？' },
    police_stormram              = { name = 'police_stormram', label = '冲击锤', weight = 18000, type = 'item', image = 'police_stormram.png', unique = false, useable = true, shouldClose = true, description = '一个不错的工具，用来砸开门' },
    empty_evidence_bag           = { name = 'empty_evidence_bag', label = '空证据袋', weight = 0, type = 'item', image = 'evidence.png', unique = false, useable = false, shouldClose = false, description = '常用于保存血液、子弹壳等的 DNA' },
    filled_evidence_bag          = { name = 'filled_evidence_bag', label = '证据袋', weight = 200, type = 'item', image = 'evidence.png', unique = true, useable = false, shouldClose = false, description = '一个装满证据的袋子，用来调查是谁犯下了罪行 >:(' },

    -- 烟花工具
    firework1                    = { name = 'firework1', label = '双兄弟', weight = 1000, type = 'item', image = 'firework1.png', unique = false, useable = true, shouldClose = true, description = '响得很' },
    firework2                    = { name = 'firework2', label = 'per per', weight = 1000, type = 'item', image = 'firework2.png', unique = false, useable = true, shouldClose = true, description = '烟花' },
    firework3                    = { name = 'firework3', label = '摔炮', weight = 1000, type = 'item', image = 'firework3.png', unique = false, useable = true, shouldClose = true, description = '这没玩过？' },
    firework4                    = { name = 'firework4', label = '垂柳', weight = 1000, type = 'item', image = 'firework4.png', unique = false, useable = true, shouldClose = true, description = '这你没玩过' },

    -- 海洋工具
    dendrogyra_coral             = { name = 'dendrogyra_coral', label = '柱状珊瑚', weight = 1000, type = 'item', image = 'dendrogyra_coral.png', unique = false, useable = false, shouldClose = true, description = '也叫柱状珊瑚' },
    antipatharia_coral           = { name = 'antipatharia_coral', label = '黑珊瑚', weight = 1000, type = 'item', image = 'antipatharia_coral.png', unique = false, useable = false, shouldClose = true, description = '也叫黑珊瑚或刺珊瑚' },
    diving_gear                  = { name = 'diving_gear', label = '潜水装备', weight = 30000, type = 'item', image = 'diving_gear.png', unique = true, useable = true, shouldClose = true, description = '一套氧气瓶和潜水呼吸器' },
    diving_fill                  = { name = 'diving_fill', label = '潜水管', weight = 3000, type = 'item', image = 'diving_tube.png', unique = true, useable = true, shouldClose = true, description = '一根氧气管和潜水呼吸器' },

    -- Other Tools
    casinochips                  = { name = 'casinochips', label = '赌场筹码', weight = 0, type = 'item', image = 'casinochips.png', unique = false, useable = false, shouldClose = false, description = '用于赌场赌博的筹码' },
    stickynote                   = { name = 'stickynote', label = '便利贴', weight = 0, type = 'item', image = 'stickynote.png', unique = true, useable = false, shouldClose = false, description = '有时可以用来记住一些事情 :)' },
    moneybag                     = { name = 'moneybag', label = '钱袋', weight = 0, type = 'item', image = 'moneybag.png', unique = true, useable = true, shouldClose = true, description = '装有现金的袋子' },
    parachute                    = { name = 'parachute', label = '降落伞', weight = 30000, type = 'item', image = 'parachute.png', unique = true, useable = true, shouldClose = true, description = '天空是极限！嗨！' },
    binoculars                   = { name = 'binoculars', label = '双筒望远镜', weight = 600, type = 'item', image = 'binoculars.png', unique = false, useable = true, shouldClose = true, description = '偷偷摸摸的...'} ,
    lighter                      = { name = 'lighter', label = '打火机', weight = 0, type = 'item', image = 'lighter.png', unique = false, useable = false, shouldClose = true, description = '在新年夜，站在火堆旁边真是太好了' },
    certificate                  = { name = 'certificate', label = '证书', weight = 0, type = 'item', image = 'certificate.png', unique = false, useable = false, shouldClose = true, description = '证明你拥有某些物品的证书' },
    markedbills                  = { name = 'markedbills', label = '标记钱币', weight = 1000, type = 'item', image = 'markedbills.png', unique = true, useable = false, shouldClose = true, description = '钱？' },
    labkey                       = { name = 'labkey', label = '钥匙', weight = 500, type = 'item', image = 'labkey.png', unique = true, useable = true, shouldClose = true, description = '一把锁的钥匙...?' },
    printerdocument              = { name = 'printerdocument', label = '文件', weight = 500, type = 'item', image = 'printerdocument.png', unique = true, useable = true, shouldClose = true, description = '一份不错的文件' },
    newscam                      = { name = 'newscam', label = '新闻摄像机', weight = 100, type = 'item', image = 'newscam.png', unique = true, useable = true, shouldClose = true, description = '新闻用摄像机' },
    newsmic                      = { name = 'newsmic', label = '新闻麦克风', weight = 100, type = 'item', image = 'newsmic.png', unique = true, useable = true, shouldClose = true, description = '新闻用麦克风' },
    newsbmic                     = { name = 'newsbmic', label = '新闻话筒', weight = 100, type = 'item', image = 'newsbmic.png', unique = true, useable = true, shouldClose = true, description = '可用的新闻话筒' },

    -- custom:fishing
    tuna                          = { name = 'tuna', label = '金枪鱼', weight = 10000, type = 'item', image = 'tuna.png', unique = false, useable = false, shouldClose = true, description = '' },
    titanium_rod                  = { name = 'titanium_rod', label = '钛合金钓竿', weight = 450, type = 'item', image = 'titanium_rod.png', unique = false, useable = true, shouldClose = true, description = '' },
    basic_rod                     = { name = 'basic_rod', label = '基础钓竿', weight = 250, type = 'item', image = 'basic_rod.png', unique = false, useable = true, shouldClose = true, description = '' },
    anchovy                       = { name = 'anchovy', label = '鳀鱼', weight = 20, type = 'item', image = 'anchovy.png', unique = false, useable = false, shouldClose = true, description = '' },
    shark                         = { name = 'shark', label = '鲨鱼', weight = 7500, type = 'item', image = 'shark.png', unique = false, useable = false, shouldClose = true, description = '' },
    mahi_mahi                     = { name = 'mahi_mahi', label = '马哈马哈', weight = 3500, type = 'item', image = 'mahi_mahi.png', unique = false, useable = false, shouldClose = true, description = '' },
    trout                         = { name = 'trout', label = '鳟鱼', weight = 750, type = 'item', image = 'trout.png', unique = false, useable = false, shouldClose = true, description = '' },
    salmon                        = { name = 'salmon', label = '鲑鱼', weight = 1000, type = 'item', image = 'salmon.png', unique = false, useable = false, shouldClose = true, description = '' },
    red_snapper                   = { name = 'red_snapper', label = '红鲷鱼', weight = 2500, type = 'item', image = 'red_snapper.png', unique = false, useable = false, shouldClose = true, description = '' },
    piranha                       = { name = 'piranha', label = '食人鱼', weight = 1500, type = 'item', image = 'piranha.png', unique = false, useable = false, shouldClose = true, description = '' },
    graphite_rod                  = { name = 'graphite_rod', label = '石墨钓竿', weight = 350, type = 'item', image = 'graphite_rod.png', unique = false, useable = true, shouldClose = true, description = '' },
    worms                         = { name = 'worms', label = '虫饵', weight = 10, type = 'item', image = 'worms.png', unique = false, useable = false, shouldClose = true, description = '' },
    haddock                       = { name = 'haddock', label = '黑线鳕', weight = 500, type = 'item', image = 'haddock.png', unique = false, useable = false, shouldClose = true, description = '' },
    grouper                       = { name = 'grouper', label = '石斑鱼', weight = 3500, type = 'item', image = 'grouper.png', unique = false, useable = false, shouldClose = true, description = '' },
    artificial_bait               = { name = 'artificial_bait', label = '人工饵', weight = 30, type = 'item', image = 'artificial_bait.png', unique = false, useable = false, shouldClose = true, description = '' },
}
