QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = '公民', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '自由职业者', payment = 200 } } },
	bus = { label = '公交车司机', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '司机', payment = 500 } } },
	judge = { label = '荣誉法官', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '法官', payment = 500 } } },
	lawyer = { label = '律师事务所', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '助理', payment = 500 } } },
	reporter = { label = '记者', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '新闻记者', payment = 500 } } },
	trucker = { label = '卡车司机', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '司机', payment = 500 } } },
	tow = { label = '拖车服务', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '司机', payment = 500 } } },
	garbage = { label = '垃圾收集', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '收集员', payment = 500 } } },
	vineyard = { label = '葡萄园', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '采摘员', payment = 500 } } },
	hotdog = { label = '热狗摊', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '销售员', payment = 500 } } },
	delivery = { label = '邮政员', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '邮政员', payment = 200 } } },

	police = {
		label = '警察',
		type = 'leo',  -- law enforcement offer 执法人员
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 500 },
			['1'] = { name = '初级警员', payment = 600 },
			['2'] = { name = '警长', payment = 700 },
			['3'] = { name = '警督', payment = 800 },
			['4'] = { name = '警察局长', isboss = true, payment = 1000 },
		},
	},
	ambulance = {
		label = '医护',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 500 },
			['1'] = { name = '护理人员', payment = 600 },
			['2'] = { name = '医生', payment = 700 },
			['3'] = { name = '主治医师', payment = 800 },
			['4'] = { name = '医院长', isboss = true, payment = 1000 },
		},
	},
	realestate = {
		label = '房地产',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 500 },
			['1'] = { name = '销售', payment = 600 },
			['2'] = { name = '销售经理', payment = 700 },
			['3'] = { name = '经纪人', payment = 800 },
			['4'] = { name = '老板', isboss = true, payment = 1000 },
		},
	},
	taxi = {
		label = '出租车',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 200 },
			['1'] = { name = '司机', payment = 200 },
			['2'] = { name = '老司机', payment = 200 },
			['3'] = { name = '管理者', payment = 200 },
			['4'] = { name = '老板', isboss = true, payment = 200 },
		},
	},
	cardealer = {
		label = '车企',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 500 },
			['1'] = { name = '展厅销售', payment = 600 },
			['2'] = { name = '销售经理', payment = 700 },
			['3'] = { name = '首席财务执行官', payment = 800 },
			['4'] = { name = '老板', isboss = true, payment = 1000 },
		},
	},
	mechanic = {
		label = '修车厂',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级修理工', payment = 500 },
			['1'] = { name = '中级修理工', payment = 600 },
			['2'] = { name = '高级修理工', payment = 700 },
			['3'] = { name = '特技修理工', payment = 800 },
			['4'] = { name = '老板', isboss = true, payment = 1000 },
		},
	},
	mechanic2 = {
		label = '修车厂',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级修理工', payment = 500 },
			['1'] = { name = '中级修理工', payment = 600 },
			['2'] = { name = '高级修理工', payment = 700 },
			['3'] = { name = '特级修理工', payment = 800 },
			['4'] = { name = '老板', isboss = true, payment = 1000 },
		},
	},
	mechanic3 = {
		label = '修车厂',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级修理工', payment = 500 },
			['1'] = { name = '中级修理工', payment = 600 },
			['2'] = { name = '高级修理工', payment = 700 },
			['3'] = { name = '特级修理工', payment = 800 },
			['4'] = { name = '老板', isboss = true, payment = 1000 },
		},
	},
	beeker = {
		label = '改车坊',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级改装工', payment = 500 },
			['1'] = { name = '中级改装工', payment = 600 },
			['2'] = { name = '高级改装工', payment = 700 },
			['3'] = { name = '特级改装工', payment = 800 },
			['4'] = { name = '老板', isboss = true, payment = 1000 },
		},
	},
	bennys = {
		label = '改车坊',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级改装工', payment = 500 },
			['1'] = { name = '中级改装工', payment = 600 },
			['2'] = { name = '高级改装工', payment = 700 },
			['3'] = { name = '特级改装工', payment = 800 },
			['4'] = { name = '老板', isboss = true, payment = 1000 },
		},
	},
}
