QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 10 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	judge = { label = 'Honorary', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Judge', payment = 100 } } },
	lawyer = { label = 'Law Firm', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associate', payment = 50 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 50 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 50 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 50 } } },

	police = {
		label = '警察',
		type = 'leo',  -- law enforcement offer 执法人员
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 1000 },
			['1'] = { name = '初级警员', payment = 1300 },
			['2'] = { name = '警长', payment = 1700 },
			['3'] = { name = '警督', payment = 2200 },
			['4'] = { name = '警察局长', isboss = true, payment = 3000 },
		},
	},
	ambulance = {
		label = '医护',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 800 },
			['1'] = { name = '护理人员', payment = 1200 },
			['2'] = { name = '医生', payment = 1700 },
			['3'] = { name = '主治医师', payment = 2300 },
			['4'] = { name = '医院长', isboss = true, payment = 3500 },
		},
	},
	realestate = {
		label = '房地产',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 500 },
			['1'] = { name = '销售', payment = 900 },
			['2'] = { name = '销售经理', payment = 1400 },
			['3'] = { name = '经纪人', payment = 2000 },
			['4'] = { name = '老板', isboss = true, payment = 3700 },
		},
	},
	taxi = {
		label = '出租车',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 500 },
			['1'] = { name = '司机', payment = 800 },
			['2'] = { name = '老司机', payment = 1200 },
			['3'] = { name = '管理者', payment = 1700 },
			['4'] = { name = '老板', isboss = true, payment = 2700 },
		},
	},
	cardealer = {
		label = '车企',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '菜鸟', payment = 500 },
			['1'] = { name = '展厅销售', payment = 1000 },
			['2'] = { name = '销售经理', payment = 1600 },
			['3'] = { name = '首席财务执行官', payment = 2300 },
			['4'] = { name = '老板', isboss = true, payment = 3600 },
		},
	},
	mechanic = {
		label = '修车厂',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级修理工', payment = 600 },
			['1'] = { name = '中级修理工', payment = 1200 },
			['2'] = { name = '高级修理工', payment = 1800 },
			['3'] = { name = '特技修理工', payment = 2400 },
			['4'] = { name = '老板', isboss = true, payment = 3600 },
		},
	},
	mechanic2 = {
		label = '修车厂',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级修理工', payment = 600 },
			['1'] = { name = '中级修理工', payment = 1200 },
			['2'] = { name = '高级修理工', payment = 1800 },
			['3'] = { name = '特级修理工', payment = 2400 },
			['4'] = { name = '老板', isboss = true, payment = 3600 },
		},
	},
	mechanic3 = {
		label = '修车厂',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级修理工', payment = 600 },
			['1'] = { name = '中级修理工', payment = 1200 },
			['2'] = { name = '高级修理工', payment = 1800 },
			['3'] = { name = '特级修理工', payment = 2400 },
			['4'] = { name = '老板', isboss = true, payment = 3600 },
		},
	},
	beeker = {
		label = '改车坊',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级改装工', payment = 600 },
			['1'] = { name = '中级改装工', payment = 1200 },
			['2'] = { name = '高级改装工', payment = 1800 },
			['3'] = { name = '特级改装工', payment = 2400 },
			['4'] = { name = '老板', isboss = true, payment = 3600 },
		},
	},
	bennys = {
		label = '改车坊',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = '初级改装工', payment = 600 },
			['1'] = { name = '中级改装工', payment = 1200 },
			['2'] = { name = '高级改装工', payment = 1800 },
			['3'] = { name = '特级改装工', payment = 2400 },
			['4'] = { name = '老板', isboss = true, payment = 3600 },
		},
	},
}
