Config = Config or {}

Config.Debug = false -- Set to True to enable Debug Prints
Config.MoneyType = 'bank'
Config.RepairMoneyType = 'cash'
Config.UseRadial = false -- Will use qb-radial menu for entering instead of press E
Config.allowGovPlateIndex = false -- Setting this to true will allow all vehicles to purchase gov plate index "Blue on White #3" (only for emergency vehicles otherwise)
maxVehiclePerformanceUpgrades = 0 -- | All Upgrades: 0 | No Upgrades: -1 | Can be -1 to 4

-- ADJUST PRICING
vehicleCustomisationPrices = {
    cosmetics = {price = 400},
    respray = {price = 1000},
    performance = {prices = {0, 3250, 5500, 10450, 15250, 20500, 25000}},
    turbo = {prices = {0, 15000}},
    wheels = {price = 400},
    customwheels = {price = 600},
    wheelsmoke = {price = 400},
    windowtint = {price = 400},
    neonside = {price = 100},
    neoncolours = {price = 500},
    headlights = {price = 100},
    xenoncolours = {price = 500},
    oldlivery = {price = 500},
    plateindex = {price = 1000}
}

-- 车辆喷漆分类
vehicleResprayCategories = {
    {category = "主色", id = 0},
    {category = "副色", id = 1},
    {category = "珠光色", id = 2},
    {category = "轮圈色", id = 3},
    {category = "仪表盘颜色", id = 4},
    {category = "内饰颜色", id = 5}
}

-- 车窗色调

vehicleWindowTintOptions = {
    {name = "无", id = 0},
    {name = "纯黑", id = 1},
    {name = "深烟雾", id = 2},
    {name = "浅烟雾", id = 3}
}

-- 前大灯

vehicleXenonOptions = {
    xenonColours = {
        {name = "原色", id = 255},
        {name = "白色", id = 0}, 
        {name = "蓝色", id = 1},
        {name = "电光蓝", id = 2},
        {name = "薄荷绿", id = 3},
        {name = "酸橙绿", id = 4},
        {name = "黄色", id = 5},
        {name = "金色喷泉", id = 6},
        {name = "橙色", id = 7},
        {name = "红色", id = 8},
        {name = "小马粉", id = 9},
        {name = "热粉", id = 10},
        {name = "紫色", id = 11},
        {name = "黑光", id = 12}
    }
}

-- 车辆轮胎选项

vehicleWheelOptions = {
    {category = "自定义轮胎", id = -1, wheelID = 23},
    {category = "轮胎烟雾", id = 20, wheelID = 23},
    {category = "运动型", id = 0, wheelID = 23},
    {category = "肌肉型", id = 1, wheelID = 23},
    {category = "低底盘", id = 2, wheelID = 23},
    {category = "SUV", id = 3, wheelID = 23},
    {category = "越野型", id = 4, wheelID = 23},
    {category = "调教型", id = 5, wheelID = 23},
    {category = "摩托车", id = 6, wheelID = 23},
    {category = "高端型", id = 7, wheelID = 23},
    {category = "本尼轮圈", id = 8, wheelID = 23},
    {category = "定制轮圈", id = 9, wheelID = 23},
    {category = "竞速型", id = 10, wheelID = 23},
    {category = "街道型", id = 11, wheelID = 23},
    {category = "拉力型", id = 12, wheelID = 23},
}

-- 轮胎烟雾颜色

vehicleTyreSmokeOptions = {
    { name = "白色烟雾", r = 254, g = 254, b = 254},
    { name = "黑色烟雾", r = 1, g = 1, b = 1},
    { name = "蓝色烟雾", r = 0, g = 150, b = 255},
    { name = "黄色烟雾", r = 255, g = 255, b = 50},
    { name = "橙色烟雾", r = 255, g = 153, b = 51},
    { name = "红色烟雾", r = 255, g = 10, b = 10},
    { name = "绿色烟雾", r = 10, g = 255, b = 10},
    { name = "紫色烟雾", r = 153, g = 10, b = 153},
    { name = "粉色烟雾", r = 255, g = 102, b = 178},
    { name = "灰色烟雾", r = 128, g = 128, b = 128}
}

-- 底光

vehicleNeonOptions = {
    category = "底光",
    neonTypes = {
        {name = "前底光", id = 2},
        {name = "后底光", id = 3},
        {name = "左底光", id = 0},
        {name = "右底光", id = 1}
    },
    neonColours = {
        { name = "白色", r = 222, g = 222, b = 255},
        { name = "蓝色", r = 2, g = 21, b = 255},
        { name = "电光蓝", r = 3, g = 83, b = 255},
        { name = "薄荷绿", r = 0, g = 255, b = 140},
        { name = "酸橙绿", r = 94, g = 255, b = 1},
        { name = "黄色", r = 255, g = 255, b = 0},
        { name = "金色喷泉", r = 255, g = 150, b = 0},
        { name = "橙色", r = 255, g = 62, b = 0},
        { name = "红色", r = 255, g = 1, b = 1},
        { name = "小马粉", r = 255, g = 50, b = 100},
        { name = "热粉", r = 255, g = 5, b = 190},
        { name = "紫色", r = 35, g = 1, b = 255},
        { name = "黑光", r = 15, g = 3, b = 255}
    }
}

-- 主要部件

vehicleCustomisation = {
    {category = "尾翼", id = 0},
    {category = "前保险杠", id = 1},
    {category = "后保险杠", id = 2},
    {category = "侧裙", id = 3},
    {category = "排气管", id = 4},
    {category = "防滚架", id = 5},
    {category = "进气格栅", id = 6},
    {category = "引擎盖", id = 7},
    {category = "左翼子板", id = 8},
    {category = "右翼子板", id = 9},
    {category = "车顶", id = 10},
    {category = "引擎升级", id = 11},
    {category = "刹车升级", id = 12},
    {category = "变速器升级", id = 13},
    {category = "悬挂升级", id = 15},
    {category = "装甲升级", id = 16},
    {category = "涡轮升级", id = 18},
    {category = "个性车牌", id = 25},
    {category = "装饰 A", id = 27},
    {category = "装饰物", id = 28},
    {category = "仪表盘", id = 29},
    {category = "表盘", id = 30},
    {category = "车门扬声器", id = 31},
    {category = "座椅", id = 32},
    {category = "方向盘", id = 33},
    {category = "换挡杆", id = 34},
    {category = "铭牌", id = 35},
    {category = "扬声器", id = 36},
    {category = "后备厢", id = 37},
    {category = "液压系统", id = 38},
    {category = "发动机区", id = 39},
    {category = "空气滤清器", id = 40},
    {category = "支撑杆", id = 41},
    {category = "轮拱罩", id = 42},
    {category = "天线", id = 43},
    {category = "装饰 B", id = 44},
    {category = "油箱", id = 45},
    {category = "窗户", id = 46},
    {category = "涂装", id = 48},
    {category = "喇叭", id = 14,
        hornNames = {
            {name = "卡车喇叭", id = 0},
            {name = "警车喇叭", id = 1},
            {name = "小丑喇叭", id = 2},
            {name = "音乐喇叭 1", id = 3},
            {name = "音乐喇叭 2", id = 4},
            {name = "音乐喇叭 3", id = 5},
            {name = "音乐喇叭 4", id = 6},
            {name = "音乐喇叭 5", id = 7},
            {name = "悲伤长号", id = 8},
            {name = "古典喇叭 1", id = 9},
            {name = "古典喇叭 2", id = 10},
            {name = "古典喇叭 3", id = 11},
            {name = "古典喇叭 4", id = 12},
            {name = "古典喇叭 5", id = 13},
            {name = "古典喇叭 6", id = 14},
            {name = "古典喇叭 7", id = 15},
            {name = "音阶 - Do", id = 16},
            {name = "音阶 - Re", id = 17},
            {name = "音阶 - Mi", id = 18},
            {name = "音阶 - Fa", id = 19},
            {name = "音阶 - Sol", id = 20},
            {name = "音阶 - La", id = 21},
            {name = "音阶 - Ti", id = 22},
            {name = "音阶 - Do", id = 23},
            {name = "爵士喇叭 1", id = 24},
            {name = "爵士喇叭 2", id = 25},
            {name = "爵士喇叭 3", id = 26},
            {name = "爵士喇叭 循环", id = 27},
            {name = "星条旗 1", id = 28},
            {name = "星条旗 2", id = 29},
            {name = "星条旗 3", id = 30},
            {name = "星条旗 4", id = 31},
            {name = "古典喇叭 8 循环", id = 32},
            {name = "古典喇叭 9 循环", id = 33},
            {name = "古典喇叭 10 循环", id = 34},
            {name = "古典喇叭 8", id = 35},
            {name = "古典喇叭 9", id = 36},
            {name = "古典喇叭 10", id = 37},
            {name = "葬礼 循环", id = 38},
            {name = "葬礼", id = 39},
            {name = "鬼怪 循环", id = 40},
            {name = "鬼怪", id = 41},
            {name = "圣安地列斯 循环", id = 42},
            {name = "圣安地列斯", id = 43},
            {name = "自由城 循环", id = 44},
            {name = "自由城", id = 45},
            {name = "节日 1 循环", id = 46},
            {name = "节日 1", id = 47},
            {name = "节日 2 循环", id = 48},
            {name = "节日 2", id = 49},
            {name = "节日 3 循环", id = 50},
            {name = "节日 3", id = 51}
        }
    }
}

-- COLORS

vehicleResprayOptions = {
    {category = "经典", id = 0,
        colours = {
            {name = "黑色", id = 0},
            {name = "碳黑", id = 147},
            {name = "石墨灰", id = 1},
            {name = "煤黑", id = 11},
            {name = "黑钢", id = 11},
            {name = "深钢灰", id = 3},
            {name = "银色", id = 4},
            {name = "蓝银", id = 5},
            {name = "滚钢", id = 6},
            {name = "影银", id = 7},
            {name = "石银", id = 8},
            {name = "午夜银", id = 9},
            {name = "铸铁银", id = 10},
            {name = "红色", id = 27},
            {name = "托里诺红", id = 28},
            {name = "方程式红", id = 29},
            {name = "岩浆红", id = 150},
            {name = "烈焰红", id = 30},
            {name = "优雅红", id = 31},
            {name = "石榴红", id = 32},
            {name = "夕阳红", id = 33},
            {name = "赤霞珠红", id = 34},
            {name = "葡萄酒红", id = 143},
            {name = "糖果红", id = 35},
            {name = "热粉", id = 135},
            {name = "Pfsiter粉", id = 137},
            {name = "鲑鱼粉", id = 136},
            {name = "日出橙", id = 36},
            {name = "橙色", id = 38},
            {name = "亮橙", id = 138},
            {name = "金色", id = 99},
            {name = "青铜", id = 90},
            {name = "黄色", id = 88},
            {name = "赛道黄", id = 89},
            {name = "露水黄", id = 91},
            {name = "深绿色", id = 49},
            {name = "赛车绿", id = 50},
            {name = "海绿色", id = 51},
            {name = "橄榄绿", id = 52},
            {name = "亮绿色", id = 53},
            {name = "汽油绿", id = 54},
            {name = "石灰绿", id = 92},
            {name = "午夜蓝", id = 141},
            {name = "银河蓝", id = 61},
            {name = "深蓝", id = 62},
            {name = "萨克森蓝", id = 63},
            {name = "蓝色", id = 64},
            {name = "海员蓝", id = 65},
            {name = "港湾蓝", id = 66},
            {name = "钻石蓝", id = 67},
            {name = "冲浪蓝", id = 68},
            {name = "航海蓝", id = 69},
            {name = "赛车蓝", id = 73},
            {name = "超蓝", id = 70},
            {name = "浅蓝", id = 74},
            {name = "巧克力棕", id = 96},
            {name = "野牛棕", id = 101},
            {name = "鳄鱼棕", id = 95},
            {name = "费尔茨棕", id = 94},
            {name = "枫木棕", id = 97},
            {name = "山毛榉棕", id = 103},
            {name = "赤褐棕", id = 104},
            {name = "鞍棕", id = 98},
            {name = "苔藓棕", id = 100},
            {name = "木栎棕", id = 102},
            {name = "稻草棕", id = 99},
            {name = "沙棕", id = 105},
            {name = "漂白棕", id = 106},
            {name = "沙夫特紫", id = 71},
            {name = "风帆紫", id = 72},
            {name = "午夜紫", id = 142},
            {name = "亮紫", id = 145},
            {name = "奶油色", id = 107},
            {name = "冰雪白", id = 111},
            {name = "霜白", id = 112}
        }
    },
    {category = "金属", id = 1,
        colours = {
            {name = "黑色", id = 0},
            {name = "碳黑", id = 147},
            {name = "石墨灰", id = 1},
            {name = "煤黑", id = 11},
            {name = "黑钢", id = 11},
            {name = "深钢灰", id = 3},
            {name = "银色", id = 4},
            {name = "蓝银", id = 5},
            {name = "滚钢", id = 6},
            {name = "影银", id = 7},
            {name = "石银", id = 8},
            {name = "午夜银", id = 9},
            {name = "铸铁银", id = 10},
            {name = "红色", id = 27},
            {name = "托里诺红", id = 28},
            {name = "方程式红", id = 29},
            {name = "岩浆红", id = 150},
            {name = "烈焰红", id = 30},
            {name = "优雅红", id = 31},
            {name = "石榴红", id = 32},
            {name = "夕阳红", id = 33},
            {name = "赤霞珠红", id = 34},
            {name = "葡萄酒红", id = 143},
            {name = "糖果红", id = 35},
            {name = "热粉", id = 135},
            {name = "Pfsiter粉", id = 137},
            {name = "鲑鱼粉", id = 136},
            {name = "日出橙", id = 36},
            {name = "橙色", id = 38},
            {name = "亮橙", id = 138},
            {name = "金色", id = 99},
            {name = "青铜", id = 90},
            {name = "黄色", id = 88},
            {name = "赛道黄", id = 89},
            {name = "露水黄", id = 91},
            {name = "深绿色", id = 49},
            {name = "赛车绿", id = 50},
            {name = "海绿色", id = 51},
            {name = "橄榄绿", id = 52},
            {name = "亮绿色", id = 53},
            {name = "汽油绿", id = 54},
            {name = "石灰绿", id = 92},
            {name = "午夜蓝", id = 141},
            {name = "银河蓝", id = 61},
            {name = "深蓝", id = 62},
            {name = "萨克森蓝", id = 63},
            {name = "蓝色", id = 64},
            {name = "海员蓝", id = 65},
            {name = "港湾蓝", id = 66},
            {name = "钻石蓝", id = 67},
            {name = "冲浪蓝", id = 68},
            {name = "航海蓝", id = 69},
            {name = "赛车蓝", id = 73},
            {name = "超蓝", id = 70},
            {name = "浅蓝", id = 74},
            {name = "巧克力棕", id = 96},
            {name = "野牛棕", id = 101},
            {name = "鳄鱼棕", id = 95},
            {name = "费尔茨棕", id = 94},
            {name = "枫木棕", id = 97},
            {name = "山毛榉棕", id = 103},
            {name = "赤褐棕", id = 104},
            {name = "鞍棕", id = 98},
            {name = "苔藓棕", id = 100},
            {name = "木栎棕", id = 102},
            {name = "稻草棕", id = 99},
            {name = "沙棕", id = 105},
            {name = "漂白棕", id = 106},
            {name = "沙夫特紫", id = 71},
            {name = "风帆紫", id = 72},
            {name = "午夜紫", id = 142},
            {name = "亮紫", id = 145},
            {name = "奶油色", id = 107},
            {name = "冰雪白", id = 111},
            {name = "霜白", id = 112}
        }
    },
    {category = "哑光", id = 2,
        colours = {
            {name = "黑色", id = 12},
            {name = "灰色", id = 13},
            {name = "浅灰", id = 14},
            {name = "冰雪白", id = 131},
            {name = "蓝色", id = 83},
            {name = "深蓝", id = 82},
            {name = "午夜蓝", id = 84},
            {name = "午夜紫", id = 149},
            {name = "沙夫特紫", id = 148},
            {name = "红色", id = 39},
            {name = "深红", id = 40},
            {name = "橙色", id = 41},
            {name = "黄色", id = 42},
            {name = "石灰绿", id = 55},
            {name = "绿色", id = 128},
            {name = "森林绿", id = 151},
            {name = "林地绿", id = 155},
            {name = "橄榄土", id = 152},
            {name = "深土", id = 153},
            {name = "沙漠棕", id = 154}
        }
    },
    {category = "金属", id = 3,
        colours = {
            {name = "拉丝钢", id = 117},
            {name = "拉丝黑钢", id = 118},
            {name = "拉丝铝", id = 119},
            {name = "纯金", id = 158},
            {name = "拉丝金", id = 159},
            {name = "铬", id = 120}
        }
    }
}
